program = { env = "AUREUM_TEST_EXEC" }
program_arguments = ["list", "--help"]

expected_stdout = """
List tests

Usage: aureum list [OPTIONS] <PATHS>...

Arguments:
  <PATHS>...  Paths to config files

Options:
      --tree     Display tests as a tree
      --verbose  Print extra information about config files
  -h, --help     Print help
"""
expected_stderr = ""
expected_exit_code = 0
