program = { env = "AUREUM_TEST_EXEC" }
program_arguments = ["test", "--help"]

expected_stdout = """
Run tests

Usage: aureum test [OPTIONS] <PATHS>...

Arguments:
  <PATHS>...  Paths to config files

Options:
      --output-format <OUTPUT_FORMAT>  Options: summary, tap [default: summary]
      --run-tests-in-parallel          Run tests in parallel
      --verbose                        Print extra information about config files
  -h, --help                           Print help
"""
expected_stderr = ""
expected_exit_code = 0
