program = { env = "AUREUM_TEST_EXEC" }
program_arguments = ["validate"]

expected_stdout = ""
expected_stderr = """
error: the following required arguments were not provided:
  <PATHS>...

Usage: aureum validate <PATHS>...

For more information, try '--help'.
"""
expected_exit_code = 2
