program = { from_env = "AUREUM_TEST_EXEC" }


[[test]]
id = "single-valid-file"
program_arguments = ["validate", { path_of_file = "helpers/passing-test.toml" }]

expected_stdout = """
✔ helpers/passing-test.toml  1 test
"""
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "multiple-valid-files"
program_arguments = [
    "validate",
    { path_of_file = "helpers/passing-test.toml" },
    { path_of_file = "helpers/passing-test2.toml" },
]

expected_stdout = """
✔ helpers/passing-test.toml   1 test
✔ helpers/passing-test2.toml  1 test
"""
expected_stderr = ""
expected_exit_code = 0
