program = { env = "AUREUM_TEST_EXEC" }


[tests.specific_test_id]
program_arguments = [
    "run",
    "--format",
    "passthrough",
    "helpers/echo_tests.toml:test1",
]
expected_stdout = "Test 1"
expected_stderr = ""
expected_exit_code = 0


[tests.multiple_tests]
program_arguments = [
    "run",
    "--format",
    "passthrough",
    "helpers/echo_tests.toml",
]
expected_stdout = ""
expected_stderr = """
error: `--format passthrough` supports only a single test, but found 2 tests
hint: Use `--format toml` to run multiple tests, or run the `list` command to list all tests
"""
expected_exit_code = 2


[tests.missing_program_on_test1]
program_arguments = [
    "run",
    "--format",
    "passthrough",
    "helpers/missing_program_on_test1.toml",
]
expected_stdout = ""
expected_stderr = """
error: `--format passthrough` supports only a single test, but found 2 tests
hint: Use `--format toml` to run multiple tests, or run the `list` command to list all tests
"""
expected_exit_code = 2


[tests.missing_program_on_test1_run_specific_test_id]
program_arguments = [
    "run",
    "--format",
    "passthrough",
    "helpers/missing_program_on_test1.toml:test2",
]
expected_stdout = "Test 2"
expected_stderr = ""
expected_exit_code = 0


[tests.missing_program_on_all_tests]
program_arguments = [
    "run",
    "--format",
    "passthrough",
    "helpers/missing_program_on_all_tests.toml",
]
expected_stdout = ""
expected_stderr = """
error: `--format passthrough` supports only a single test, but found 2 tests
hint: Use `--format toml` to run multiple tests, or run the `list` command to list all tests
"""
expected_exit_code = 2
