input_files = ["helpers"]
program = { env = "AUREUM_TEST_EXEC" }
program_arguments = [
    "test",
    "--format",
    "summary",
    "--stable-output",
    "helpers/input-files-specific-files.toml",
    "helpers/input-files-dir.toml",
    "helpers/input-files-glob.toml",
]

expected_stdout = """
🚀 Running 3 tests:
...

Test result: OK (3 passed) — Finished in 0.0s
"""
expected_stderr = ""
expected_exit_code = 0
