program = { env = "AUREUM_TEST_EXEC" }
program_arguments = ["validate", "--help"]

expected_stdout = """
Validate config files

Usage: aureum validate [OPTIONS] <PATHS>...

Arguments:
  <PATHS>...  Paths to config files

Options:
      --hide-absolute-paths  Replace absolute paths with a platform-independent placeholder
      --verbose              Print extra information about config files
  -h, --help                 Print help
"""
expected_stderr = ""
expected_exit_code = 0
