program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "skip_root_test"
program_arguments = [
    "test",
    "--format",
    "summary",
    "helpers/skip_root_test.toml",
]

expected_stdout = """
🚀 Running 1 test:
s

Test result: OK (0 passed, 1 skipped)
"""
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "skip_subtest"
program_arguments = ["test", "--format", "summary", "helpers/skip_subtest.toml"]

expected_stdout = """
🚀 Running 2 tests:
.s

Test result: OK (1 passed, 1 skipped)
"""
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "skip_invalid_config"
program_arguments = [
    "test",
    "--format",
    "summary",
    "helpers/skip_invalid_config.toml",
]

expected_stdout = """
🚀 Running 1 test:
s

Test result: OK (0 passed, 1 skipped)
"""
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "all"
program_arguments = ["test", "--format", "summary", "helpers/*.toml"]

expected_stdout = """
🚀 Running 5 tests:
Fss.s

❌ helpers/failing_test.toml
└── Standard output
    ├── Expected
    │   ╭
    │   │ 1   │  expected
    │   ╰
    ├── Got
    │   ╭
    │   │   1 │  actual
    │   ╰
    └── Diff
        ╭
        │ 1   │ -expected
        │   1 │ +actual
        ╰

Test result: FAIL (1 passed, 3 skipped, 1 failed)
"""
expected_stderr = ""
expected_exit_code = 1
