program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "all_valid.all"
program_arguments = ["test", "--record", "100x10", "helpers/all_valid.toml"]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 2 tests                                                  0 skipped  2 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   2 / 2                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "all_valid.specific_test_id"
program_arguments = [
  "test",
  "--record",
  "100x10",
  "helpers/all_valid.toml:test1",
]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 1 test                                                   0 skipped  1 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   1 / 1                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "missing_program_on_test2.all"
program_arguments = [
  "test",
  "--record",
  "100x10",
  "helpers/missing_program_on_test2.toml",
]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 1 test                                   1 config error  0 skipped  1 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   1 / 1                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 3


[[tests]]
id = "missing_program_on_test2.specific_test_id"
program_arguments = [
  "test",
  "--record",
  "100x10",
  "helpers/missing_program_on_test2.toml:test1",
]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 1 test                                   1 config error  0 skipped  1 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   1 / 1                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 3


[[tests]]
id = "missing_program_on_all_tests"
program_arguments = [
  "test",
  "--record",
  "100x10",
  "helpers/missing_program_on_all_tests.toml",
]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 0 tests                                 2 config errors  0 skipped  0 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   0 / 0                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 3


[[tests]]
id = "missing_program_on_all_tests.specific_test_id"
program_arguments = [
  "test",
  "--record",
  "100x10",
  "helpers/missing_program_on_all_tests.toml:test1",
]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 0 tests                                 2 config errors  0 skipped  0 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   0 / 0                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 3


[[tests]]
id = "all_files"
program_arguments = ["test", "--record", "100x10", "helpers/*.toml"]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 3 tests                                 3 config errors  0 skipped  3 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   3 / 3                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 3
