program = { env = "AUREUM_TEST_EXEC" }


[[test]]
id = "missing-file"
program_arguments = ["validate", "helpers/watch-files-missing-file.toml"]

expected_stdout = """
✘ helpers/watch-files-missing-file.toml  1 test
"""
expected_stderr = """
📋 helpers/watch-files-missing-file.toml
└── Watch file errors
    └── ✘ missing external file `aureum_test_this_file_does_not_exist`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[test]]
id = "missing-env-var"
program_arguments = ["validate", "helpers/watch-files-missing-env-var.toml"]

expected_stdout = """
✘ helpers/watch-files-missing-env-var.toml  1 test
"""
expected_stderr = """
📋 helpers/watch-files-missing-env-var.toml
└── Watch file errors
    └── ✘ missing environment variable `AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3
