program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "without_verbose"
program_arguments = ["list", "helpers/*.toml"]
expected_stdout = """
helpers/many_requirements.toml:env_var_exists
helpers/many_requirements.toml:env_var_missing
helpers/many_requirements.toml:external_file_exists
helpers/many_requirements.toml:external_file_missing
helpers/no_requirements.toml
helpers/watch_files.toml:test1
helpers/watch_files.toml:test2
"""
expected_stderr = """
📋 helpers/many_requirements.toml
├── :env_var_exists
├── :env_var_missing
│   └── Validation errors
│       └── ✘ Missing environment variable 'AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST'
├── :external_file_exists
└── :external_file_missing
    └── Validation errors
        └── ✘ Missing external file 'aureum_test_this_file_does_not_exist'

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3


[[tests]]
id = "with_verbose"
program_arguments = [
    "list",
    "--verbose",
    "--hide-absolute-paths",
    "helpers/*.toml",
]
expected_stdout = """
helpers/many_requirements.toml:env_var_exists
helpers/many_requirements.toml:env_var_missing
helpers/many_requirements.toml:external_file_exists
helpers/many_requirements.toml:external_file_missing
helpers/no_requirements.toml
helpers/watch_files.toml:test1
helpers/watch_files.toml:test2
"""
expected_stderr = """
🔍 Found 3 config files
├── helpers/many_requirements.toml
├── helpers/no_requirements.toml
└── helpers/watch_files.toml

📋 helpers/many_requirements.toml
├── Requirements
│   ├── Files
│   │   ├── ✘ aureum_test_this_file_does_not_exist
│   │   └── ✔ hello_world.txt
│   └── Environment variables
│       ├── ✘ AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST
│       └── ✔ AUREUM_TEST_HELLO_WORLD
├── :env_var_exists
│   └── Program to run
│       └── ✔ <absolute path to 'echo'>
├── :env_var_missing
│   ├── Program to run
│   │   └── ✔ <absolute path to 'echo'>
│   └── Validation errors
│       └── ✘ Missing environment variable 'AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST'
├── :external_file_exists
│   └── Program to run
│       └── ✔ <absolute path to 'echo'>
└── :external_file_missing
    ├── Program to run
    │   └── ✔ <absolute path to 'echo'>
    └── Validation errors
        └── ✘ Missing external file 'aureum_test_this_file_does_not_exist'

📋 helpers/no_requirements.toml
└── Program to run
    └── ✔ <absolute path to 'echo'>

📋 helpers/watch_files.toml
├── Watch files
│   └── hello_world.txt
├── :test1
│   └── Program to run
│       └── ✔ <absolute path to 'echo'>
└── :test2
    └── Program to run
        └── ✔ <absolute path to 'echo'>

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3
