program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "without_verbose"
program_arguments = ["list", "helpers/*.toml"]

expected_stdout = """
helpers/many_requirements.toml:env_var_exists
helpers/many_requirements.toml:env_var_missing
helpers/many_requirements.toml:external_file_exists
helpers/many_requirements.toml:external_file_missing
helpers/no_requirements.toml
"""
expected_stderr = """
📋 helpers/many_requirements.toml
├── Watch file errors
│   ├── ✘ Missing external file `AUREUM_TEST_FILE_WITH_PATH_TO_WATCH_DOES_NOT_EXIST`
│   └── ✘ Missing environment variable `AUREUM_TEST_ENV_VAR_WITH_PATH_TO_WATCH_DOES_NOT_EXIST`
├── :env_var_exists
├── :env_var_missing
│   └── Validation errors
│       └── ✘ Missing environment variable `AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST`
├── :external_file_exists
└── :external_file_missing
    └── Validation errors
        └── ✘ Missing external file `aureum_test_this_file_does_not_exist`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "with_verbose"
program_arguments = [
    "list",
    "--verbose",
    "--hide-absolute-paths",
    "helpers/*.toml",
]

expected_stdout = """
helpers/many_requirements.toml:env_var_exists
helpers/many_requirements.toml:env_var_missing
helpers/many_requirements.toml:external_file_exists
helpers/many_requirements.toml:external_file_missing
helpers/no_requirements.toml
"""
expected_stderr = """
🔍 Found 2 config files
├── helpers/many_requirements.toml
└── helpers/no_requirements.toml

📋 helpers/many_requirements.toml
├── Requirements
│   ├── Files
│   │   ├── ✘ AUREUM_TEST_FILE_WITH_PATH_TO_WATCH_DOES_NOT_EXIST
│   │   ├── ✘ aureum_test_this_file_does_not_exist
│   │   └── ✔ hello_world.txt
│   └── Environment variables
│       ├── ✘ AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST
│       ├── ✘ AUREUM_TEST_ENV_VAR_WITH_PATH_TO_WATCH_DOES_NOT_EXIST
│       └── ✔ AUREUM_TEST_HELLO_WORLD
├── Watch files
│   └── hello_world.txt
├── Watch file errors
│   ├── ✘ Missing external file `AUREUM_TEST_FILE_WITH_PATH_TO_WATCH_DOES_NOT_EXIST`
│   └── ✘ Missing environment variable `AUREUM_TEST_ENV_VAR_WITH_PATH_TO_WATCH_DOES_NOT_EXIST`
├── :env_var_exists
│   └── Program to run
│       └── ✔ <absolute path to 'echo'>
├── :env_var_missing
│   ├── Program to run
│   │   └── ✔ <absolute path to 'echo'>
│   └── Validation errors
│       └── ✘ Missing environment variable `AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST`
├── :external_file_exists
│   └── Program to run
│       └── ✔ <absolute path to 'echo'>
└── :external_file_missing
    ├── Program to run
    │   └── ✔ <absolute path to 'echo'>
    └── Validation errors
        └── ✘ Missing external file `aureum_test_this_file_does_not_exist`

📋 helpers/no_requirements.toml
└── Test
    └── Program to run
        └── ✔ <absolute path to 'echo'>

warning: some config files contain errors (see above)
"""
expected_exit_code = 3
