program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "without_verbose"
program_arguments = ["run", "--format", "passthrough", "helpers/*.toml"]
expected_stdout = """
"""
expected_stderr = """
error: `--format passthrough` supports only a single test, but found 7 tests
hint: Use `--format toml` to run multiple tests, or run the `list` command to list all tests
"""
expected_exit_code = 2


[[tests]]
id = "with_verbose"
program_arguments = [
    "run",
    "--format",
    "passthrough",
    "--verbose",
    "--hide-absolute-paths",
    "helpers/*.toml",
]
expected_stdout = ""
expected_stderr = """
error: `--verbose` is not supported in passthrough mode
hint: You may want to use `--format toml` instead
"""
expected_exit_code = 2
