program = { env = "AUREUM_TEST_EXEC" }


[tests.without_verbose]
program_arguments = ["validate", "helpers/*.toml"]
expected_stdout = """
✘ helpers/many_requirements.toml  4 tests
✔ helpers/no_requirements.toml    1 test
"""
expected_stderr = """
📋 helpers/many_requirements.toml
├── :env_var_exists
├── :env_var_missing
│   └── Validation errors
│       └── ✘ Missing environment variable 'AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST'
├── :external_file_exists
└── :external_file_missing
    └── Validation errors
        └── ✘ Missing external file 'aureum_test_this_file_does_not_exist'

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3


[tests.with_verbose]
program_arguments = [
    "validate",
    "--verbose",
    "--hide-absolute-paths",
    "helpers/*.toml",
]
expected_stdout = """
✘ helpers/many_requirements.toml  4 tests
✔ helpers/no_requirements.toml    1 test
"""
expected_stderr = """
🔍 Found 2 config files
├── helpers/many_requirements.toml
└── helpers/no_requirements.toml

📋 helpers/many_requirements.toml
├── :env_var_exists
│   ├── Program to run
│   │   └── ✔ <absolute path to 'echo'>
│   └── Requirements
│       └── Environment variables
│           └── ✔ AUREUM_TEST_HELLO_WORLD
├── :env_var_missing
│   ├── Program to run
│   │   └── ✔ <absolute path to 'echo'>
│   ├── Requirements
│   │   └── Environment variables
│   │       └── ✘ AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST
│   └── Validation errors
│       └── ✘ Missing environment variable 'AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST'
├── :external_file_exists
│   ├── Program to run
│   │   └── ✔ <absolute path to 'echo'>
│   └── Requirements
│       └── Files
│           └── ✔ hello_world.txt
└── :external_file_missing
    ├── Program to run
    │   └── ✔ <absolute path to 'echo'>
    ├── Requirements
    │   └── Files
    │       └── ✘ aureum_test_this_file_does_not_exist
    └── Validation errors
        └── ✘ Missing external file 'aureum_test_this_file_does_not_exist'

📋 helpers/no_requirements.toml
└── Program to run
    └── ✔ <absolute path to 'echo'>

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3
