input_files = ["helpers/input-files-passing*.toml"]
program = { from_env = "AUREUM_TEST_EXEC" }
program_arguments = [
    "test",
    "--stable-output",
    "helpers/input-files-passing.toml",
    "helpers/input-files-passing2.toml",
]

expected_stdout = """
🚀 Running 2 tests:
..

Test result: OK (2 passed) — Finished in 0.0s
"""
expected_stderr = ""
expected_exit_code = 0
