input_files = ["helpers"]
program = { from_env = "AUREUM_TEST_EXEC" }


[[test]]
id = "default"
program_arguments = [
    "test",
    "--format=summary",
    "--stable-output",
    "helpers/path-of-file.toml",
]

expected_stdout = """
🚀 Running 1 test:
.

Test result: OK (1 passed) — Finished in 0.1s
"""
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "scratch-in-place-allows-path-of-file"
program_arguments = [
    "test",
    "--format=summary",
    "--scratch=in-place",        # Extra argument
    "--stable-output",
    "helpers/path-of-file.toml",
]

expected_stdout = """
🚀 Running 1 test:
.

Test result: OK (1 passed) — Finished in 0.1s
"""
expected_stderr = ""
expected_exit_code = 0
