program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "wrong_field_types"
program_arguments = ["validate", "helpers/wrong_field_types.toml"]
expected_stdout = """
✘ helpers/wrong_field_types.toml  Parse error
"""
expected_stderr = """
📋 helpers/wrong_field_types.toml
└── Parse errors
    ├── ✘ field `program`: expected string, got boolean
    ├── ✘ field `program_arguments`: expected array, got string
    └── ✘ field `expected_exit_code`: expected integer, got string

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3


[[tests]]
id = "wrong_array_element"
program_arguments = ["validate", "helpers/wrong_array_element.toml"]
expected_stdout = """
✘ helpers/wrong_array_element.toml  Parse error
"""
expected_stderr = """
📋 helpers/wrong_array_element.toml
└── Parse errors
    ├── ✘ field `program_arguments`: [1]: expected string, got integer
    └── ✘ field `program_arguments`: [2]: expected string, got boolean

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3
