program = { env = "AUREUM_TEST_EXEC" }
program_arguments = ["validate", "helpers/invalid_syntax.toml"]

expected_stdout = """
✘ helpers/invalid_syntax.toml  Parse error
"""
expected_stderr = """
📋 helpers/invalid_syntax.toml
└── Parse errors
    └── ✘ invalid TOML syntax: TOML parse error at line 1, column 10
          |
        1 | program =
          |          ^
        string values must be quoted, expected literal string

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3
