program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "missing_id"
program_arguments = ["validate", "helpers/missing_id.toml"]
expected_stdout = """
✘ helpers/missing_id.toml  Parse error
"""
expected_stderr = """
📋 helpers/missing_id.toml
└── Parse errors
    └── ✘ [0]: missing required field 'id'

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3


[[tests]]
id = "invalid_id"
program_arguments = ["validate", "helpers/invalid_id.toml"]
expected_stdout = """
✘ helpers/invalid_id.toml  Parse error
"""
expected_stderr = """
📋 helpers/invalid_id.toml
└── Parse errors
    ├── ✘ [1]: field 'id': invalid id 'invalid id!'
    └── ✘ [2]: field 'id': invalid id ''

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3


[[tests]]
id = "id_at_root"
program_arguments = ["validate", "helpers/id_at_root.toml"]
expected_stdout = """
✘ helpers/id_at_root.toml  Parse error
"""
expected_stderr = """
📋 helpers/id_at_root.toml
└── Parse errors
    └── ✘ 'id' is not allowed at the root level

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3
