program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "unknown_field_at_root"
program_arguments = ["validate", "helpers/unknown_field_at_root.toml"]
expected_stdout = """
✘ helpers/unknown_field_at_root.toml  Parse error
"""
expected_stderr = """
📋 helpers/unknown_field_at_root.toml
└── Parse errors
    └── ✘ unknown field 'typo_field'

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3


[[tests]]
id = "unknown_field_in_subtest"
program_arguments = ["validate", "helpers/unknown_field_in_subtest.toml"]
expected_stdout = """
✘ helpers/unknown_field_in_subtest.toml  Parse error
"""
expected_stderr = """
📋 helpers/unknown_field_in_subtest.toml
└── Parse errors
    └── ✘ [0]: unknown field 'typo_field'

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3
