program = { env = "AUREUM_TEST_EXEC" }
program_arguments = ["validate", "helpers/nested_tests.toml:test1"]

expected_stdout = """
All config files are valid
"""
expected_stderr = ""
expected_exit_code = 0
