program = { env = "AUREUM_TEST_EXEC" }


[tests.show_all_tests]
program_arguments = [
   "test",
   "--show-all-tests",
   "basic_helpers/passing_test.toml",
   "basic_helpers/failing_test.toml",
]
expected_stdout = """
🚀 Running 2 tests:
F.

❌ basic_helpers/failing_test.toml
├─ Standard output
│  ├─ Expected
│  │  ╭
│  │  │ STDOUT
│  │  ╰ (No newline at end)
│  ├─ Got
│  │  ╭
│  │  │ Hello world
│  │  ╰ (No newline at end)
│  └─ Diff
│     ╭
│     │ -STDOUT
│     │ +Hello world
│     ╰
├─ Standard error
│  ├─ Expected
│  │  ╭
│  │  │ STDERR
│  │  ╰ (No newline at end)
│  ├─ Got
│  │  ╭
│  │  │ 
│  │  ╰ (No newline at end)
│  └─ Diff
│     ╭
│     │ -STDERR
│     ╰
└─ Exit code
   ├─ Expected
   │  └─ 42
   └─ Got
      └─ 0
✅ basic_helpers/passing_test.toml

Test result: FAIL (1 passed, 1 failed)
"""
expected_stderr = ""
expected_exit_code = 1


[tests.default]
program_arguments = [
   "test",
   "basic_helpers/passing_test.toml",
   "basic_helpers/failing_test.toml",
]
expected_stdout = """
🚀 Running 2 tests:
F.

❌ basic_helpers/failing_test.toml
├─ Standard output
│  ├─ Expected
│  │  ╭
│  │  │ STDOUT
│  │  ╰ (No newline at end)
│  ├─ Got
│  │  ╭
│  │  │ Hello world
│  │  ╰ (No newline at end)
│  └─ Diff
│     ╭
│     │ -STDOUT
│     │ +Hello world
│     ╰
├─ Standard error
│  ├─ Expected
│  │  ╭
│  │  │ STDERR
│  │  ╰ (No newline at end)
│  ├─ Got
│  │  ╭
│  │  │ 
│  │  ╰ (No newline at end)
│  └─ Diff
│     ╭
│     │ -STDERR
│     ╰
└─ Exit code
   ├─ Expected
   │  └─ 42
   └─ Got
      └─ 0

Test result: FAIL (1 passed, 1 failed)
"""
expected_stderr = ""
expected_exit_code = 1
