program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "skip_root_test"
program_arguments = [
    "test",
    "--record",
    "100x20",
    "--watch",
    "helpers/skip-root-test.toml",
]

expected_stdout = { file = "snapshots/skip-root-test.txt" }
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "skip_subtest"
program_arguments = [
    "test",
    "--record",
    "100x20",
    "--watch",
    "helpers/skip-subtest.toml",
]

expected_stdout = { file = "snapshots/skip-subtest.txt" }
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "skip_invalid_config"
program_arguments = [
    "test",
    "--record",
    "100x20",
    "--watch",
    "helpers/skip-invalid-config.toml",
]

expected_stdout = { file = "snapshots/skip-invalid-config.txt" }
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "validation_error_with_skipped"
program_arguments = [
    "test",
    "--record",
    "100x20",
    "--watch",
    "helpers/validation-error-with-skipped.toml",
]

expected_stdout = { file = "snapshots/validation-error-with-skipped.txt" }
expected_stderr = ""
expected_exit_code = 3


[[tests]]
id = "all"
program_arguments = ["test", "--record", "100x20", "--watch", "helpers/*.toml"]
stdin = "r\nl\nq\n"

expected_stdout = { file = "snapshots/all.txt" }
expected_stderr = ""
expected_exit_code = 1
