program = { from_env = "AUREUM_TEST_EXEC" }


[[test]]
id = "skip-root-test"
program_arguments = [
    "test",
    "--record=100x20",
    "--watch",
    { path_of_file = "helpers/skip-root-test.toml" },
]

expected_stdout = { from_file = "snapshots/skip-root-test.txt" }
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "skip-subtest"
program_arguments = [
    "test",
    "--record=100x20",
    "--watch",
    { path_of_file = "helpers/skip-subtest.toml" },
]

expected_stdout = { from_file = "snapshots/skip-subtest.txt" }
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "skip-invalid-config"
program_arguments = [
    "test",
    "--record=100x20",
    "--watch",
    { path_of_file = "helpers/skip-invalid-config.toml" },
]

expected_stdout = { from_file = "snapshots/skip-invalid-config.txt" }
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "validation-error-with-skipped"
program_arguments = [
    "test",
    "--record=100x20",
    "--watch",
    { path_of_file = "helpers/validation-error-with-skipped.toml" },
]

expected_stdout = { from_file = "snapshots/validation-error-with-skipped.txt" }
expected_stderr = ""
expected_exit_code = 3


[[test]]
id = "all"
input_files = ["helpers"]
program_arguments = ["test", "--record=100x20", "--watch", "helpers/*.toml"]
stdin = "f\nl\nq\n"

expected_stdout = { from_file = "snapshots/all.txt" }
expected_stderr = ""
expected_exit_code = 1
