watch_files = ["hello_world.txt"]

program = "echo"


[[tests]]
id = "test1"
program_arguments = ["-n", "Test 1"]

expected_stdout = "Test 1"


[[tests]]
id = "test2"
program_arguments = ["-n", "Test 2"]

expected_stdout = "Test 2"
