program = "echo"


[[tests]]
id = "test-z"
program_arguments = ["-n", "Z"]

expected_stdout = "Z"


[[tests]]
id = "test-a"
program_arguments = ["-n", "A"]

expected_stdout = "A"


[[tests]]
id = "test-m"
program_arguments = ["-n", "M"]

expected_stdout = "M"
