program = "echo"


[[test]]
id = "passing"
program_arguments = ["hello"]

expected_stdout = "hello\n"


[[test]]
id = "not-ready"
skip = "feature not ready"
program_arguments = ["world"]

expected_stdout = "world\n"
