input_files = ["helpers"]
program = { from_env = "AUREUM_TEST_EXEC" }


[[test]]
id = "all-valid.all"
program_arguments = ["list", "helpers/all-valid.toml"]

expected_stdout = """
helpers/all-valid.toml:test1
helpers/all-valid.toml:test2
"""
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "all-valid.specific-test-id"
program_arguments = ["list", "helpers/all-valid.toml:test1"]

expected_stdout = """
helpers/all-valid.toml:test1
"""
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "missing-program-on-test2.all"
program_arguments = ["list", "helpers/missing-program-on-test2.toml"]

expected_stdout = """
helpers/missing-program-on-test2.toml:test1
helpers/missing-program-on-test2.toml:test2
"""
expected_stderr = """
📋 helpers/missing-program-on-test2.toml
├── :test1
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[test]]
id = "missing-program-on-test2.specific-test-id"
program_arguments = ["list", "helpers/missing-program-on-test2.toml:test1"]

expected_stdout = """
helpers/missing-program-on-test2.toml:test1
"""
expected_stderr = """
📋 helpers/missing-program-on-test2.toml
├── :test1
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[test]]
id = "missing-program-on-all-tests"
program_arguments = ["list", "helpers/missing-program-on-all-tests.toml"]

expected_stdout = """
helpers/missing-program-on-all-tests.toml:test1
helpers/missing-program-on-all-tests.toml:test2
"""
expected_stderr = """
📋 helpers/missing-program-on-all-tests.toml
├── :test1
│   └── Validation errors
│       └── ✘ missing required field `program`
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[test]]
id = "missing-program-on-all-tests.specific-test-id"
program_arguments = ["list", "helpers/missing-program-on-all-tests.toml:test1"]

expected_stdout = """
helpers/missing-program-on-all-tests.toml:test1
"""
expected_stderr = """
📋 helpers/missing-program-on-all-tests.toml
├── :test1
│   └── Validation errors
│       └── ✘ missing required field `program`
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[test]]
id = "all-files"
program_arguments = ["list", "helpers/*.toml"]

expected_stdout = """
helpers/all-valid.toml:test1
helpers/all-valid.toml:test2
helpers/missing-program-on-all-tests.toml:test1
helpers/missing-program-on-all-tests.toml:test2
helpers/missing-program-on-test2.toml:test1
helpers/missing-program-on-test2.toml:test2
"""
expected_stderr = """
📋 helpers/missing-program-on-all-tests.toml
├── :test1
│   └── Validation errors
│       └── ✘ missing required field `program`
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

📋 helpers/missing-program-on-test2.toml
├── :test1
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3
