program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "all_valid.all"
program_arguments = ["run", "--format", "passthrough", "helpers/all-valid.toml"]

expected_stdout = ""
expected_stderr = """
error: `--format passthrough` supports only a single test, but found 2 tests
hint: use `--format toml` to run multiple tests or run the `list` command to list all tests
"""
expected_exit_code = 2


[[tests]]
id = "all_valid.specific_test_id"
program_arguments = [
    "run",
    "--format",
    "passthrough",
    "helpers/all-valid.toml:test1",
]

expected_stdout = "Test 1"
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "missing_program_on_test2.all"
program_arguments = [
    "run",
    "--format",
    "passthrough",
    "helpers/missing-program-on-test2.toml",
]

expected_stdout = ""
expected_stderr = """
error: `--format passthrough` supports only a single test, but found 2 tests
hint: use `--format toml` to run multiple tests or run the `list` command to list all tests
"""
expected_exit_code = 2


[[tests]]
id = "missing_program_on_test2.specific_test_id"
program_arguments = [
    "run",
    "--format",
    "passthrough",
    "helpers/missing-program-on-test2.toml:test1",
]

expected_stdout = "Test 1"
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "missing_program_on_all_tests"
program_arguments = [
    "run",
    "--format",
    "passthrough",
    "helpers/missing-program-on-all-tests.toml",
]

expected_stdout = ""
expected_stderr = """
error: `--format passthrough` supports only a single test, but found 2 tests
hint: use `--format toml` to run multiple tests or run the `list` command to list all tests
"""
expected_exit_code = 2


[[tests]]
id = "missing_program_on_all_tests.specific_test_id"
program_arguments = [
    "run",
    "--format",
    "passthrough",
    "helpers/missing-program-on-all-tests.toml:test1",
]

expected_stdout = ""
expected_stderr = """
📋 helpers/missing-program-on-all-tests.toml
├── :test1
│   └── Validation errors
│       └── ✘ missing required field `program`
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "all_files"
program_arguments = ["run", "--format", "passthrough", "helpers/*.toml"]

expected_stdout = ""
expected_stderr = """
error: `--format passthrough` supports only a single test, but found 6 tests
hint: use `--format toml` to run multiple tests or run the `list` command to list all tests
"""
expected_exit_code = 2
