program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "all-valid.all"
program_arguments = [
    "test",
    "--format",
    "summary",
    "--stable-output",
    "helpers/all-valid.toml",
]

expected_stdout = """
🚀 Running 2 tests:
..

Test result: OK (2 passed) — Finished in 0.0s
"""
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "all-valid.specific-test-id"
program_arguments = [
    "test",
    "--format",
    "summary",
    "--stable-output",
    "helpers/all-valid.toml:test1",
]

expected_stdout = """
🚀 Running 1 test:
.

Test result: OK (1 passed) — Finished in 0.0s
"""
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "missing-program-on-test2.all"
program_arguments = [
    "test",
    "--format",
    "summary",
    "--stable-output",
    "helpers/missing-program-on-test2.toml",
]

expected_stdout = """
🚀 Running 1 test:
.

Test result: OK* (1 passed, 1 config error) — Finished in 0.0s
"""
expected_stderr = """
📋 helpers/missing-program-on-test2.toml
├── :test1
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "missing-program-on-test2.specific-test-id"
program_arguments = [
    "test",
    "--format",
    "summary",
    "--stable-output",
    "helpers/missing-program-on-test2.toml:test1",
]

expected_stdout = """
🚀 Running 1 test:
.

Test result: OK* (1 passed, 1 config error) — Finished in 0.0s
"""
expected_stderr = """
📋 helpers/missing-program-on-test2.toml
├── :test1
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "missing-program-on-all-tests"
program_arguments = [
    "test",
    "--format",
    "summary",
    "--stable-output",
    "helpers/missing-program-on-all-tests.toml",
]

expected_stdout = """
🚀 Running 0 tests:


Test result: OK* (0 passed, 2 config errors) — Finished in 0.0s
"""
expected_stderr = """
📋 helpers/missing-program-on-all-tests.toml
├── :test1
│   └── Validation errors
│       └── ✘ missing required field `program`
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "missing-program-on-all-tests.specific-test-id"
program_arguments = [
    "test",
    "--format",
    "summary",
    "--stable-output",
    "helpers/missing-program-on-all-tests.toml:test1",
]

expected_stdout = """
🚀 Running 0 tests:


Test result: OK* (0 passed, 2 config errors) — Finished in 0.0s
"""
expected_stderr = """
📋 helpers/missing-program-on-all-tests.toml
├── :test1
│   └── Validation errors
│       └── ✘ missing required field `program`
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "all-files"
program_arguments = [
    "test",
    "--format",
    "summary",
    "--stable-output",
    "helpers/*.toml",
]

expected_stdout = """
🚀 Running 3 tests:
...

Test result: OK* (3 passed, 3 config errors) — Finished in 0.0s
"""
expected_stderr = """
📋 helpers/missing-program-on-all-tests.toml
├── :test1
│   └── Validation errors
│       └── ✘ missing required field `program`
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

📋 helpers/missing-program-on-test2.toml
├── :test1
└── :test2
    └── Validation errors
        └── ✘ missing required field `program`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3
