input_files = ["helpers"]
program = { from_env = "AUREUM_TEST_EXEC" }


[[test]]
id = "all-valid.all"
program_arguments = ["test", "--record=100x10", "helpers/all-valid.toml"]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 2 tests                                                  0 skipped  2 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   2 / 2                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "all-valid.specific-test-id"
program_arguments = [
  "test",
  "--record=100x10",
  "helpers/all-valid.toml:test1",
]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 1 test                                                   0 skipped  1 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   1 / 1                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "missing-program-on-test2.all"
program_arguments = [
  "test",
  "--record=100x10",
  "helpers/missing-program-on-test2.toml",
]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 1 test                                   1 config error  0 skipped  1 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   1 / 1                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 3


[[test]]
id = "missing-program-on-test2.specific-test-id"
program_arguments = [
  "test",
  "--record=100x10",
  "helpers/missing-program-on-test2.toml:test1",
]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 1 test                                   1 config error  0 skipped  1 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   1 / 1                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 3


[[test]]
id = "missing-program-on-all-tests"
program_arguments = [
  "test",
  "--record=100x10",
  "helpers/missing-program-on-all-tests.toml",
]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 0 tests                                 2 config errors  0 skipped  0 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   0 / 0                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 3


[[test]]
id = "missing-program-on-all-tests.specific-test-id"
program_arguments = [
  "test",
  "--record=100x10",
  "helpers/missing-program-on-all-tests.toml:test1",
]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 0 tests                                 2 config errors  0 skipped  0 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   0 / 0                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 3


[[test]]
id = "all-files"
program_arguments = ["test", "--record=100x10", "helpers/*.toml"]

expected_stdout = """
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│  Running 3 tests                                 3 config errors  0 skipped  3 passed  0 failed  │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                  │
│                   ████████████████████████████████████████████████████████████                   │
│                   3 / 3                                                   0.0s                   │
│                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

  q: quit
"""
expected_stderr = ""
expected_exit_code = 3
