program = { env = "AUREUM_TEST_EXEC" }


[[test]]
id = "singleline"
program_arguments = [
    "run",
    "--format",
    "toml",
    "helpers/echo-hello.toml",
]

expected_stdout = """
# TEST: helpers/echo-hello.toml
expected_stdout = "Hello world"
expected_stderr = ""
expected_exit_code = 0
"""
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "multiline"
program_arguments = [
    "run",
    "--format",
    "toml",
    "helpers/echo-multiline.toml",
]

expected_stdout = """
# TEST: helpers/echo-multiline.toml
expected_stdout = \"\"\"
Hello world
\"\"\"
expected_stderr = ""
expected_exit_code = 0
"""
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "stderr-and-exit-code"
program_arguments = [
    "run",
    "--format",
    "toml",
    "helpers/bash-stderr-and-exit-code.toml",
]

expected_stdout = """
# TEST: helpers/bash-stderr-and-exit-code.toml
expected_stdout = ""
expected_stderr = "hello"
expected_exit_code = 42
"""
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "stdin"
program_arguments = ["run", "--format", "toml", "helpers/cat-stdin.toml"]

expected_stdout = """
# TEST: helpers/cat-stdin.toml
expected_stdout = "Hello world"
expected_stderr = ""
expected_exit_code = 0
"""
expected_stderr = ""
expected_exit_code = 0
