program = { from_env = "AUREUM_TEST_EXEC" }


[[test]]
id = "show-unknown"
program_arguments = [
    "list",
    "--show=UNKNOWN",
    { path_of_file = "helpers/passing-test.toml" },
]

expected_stdout = ""
expected_stderr = """
error: invalid value 'UNKNOWN' for '--show <WHICH>'
  [possible values: all, runnable, skipped]

For more information, try '--help'.
"""
expected_exit_code = 2
