input_files = ["helpers"]
program = { from_env = "AUREUM_TEST_EXEC" }
program_arguments = ["list", "helpers/*.toml"]

expected_stdout = """
helpers/nested-test.toml:test1
helpers/nested-test.toml:test2
helpers/passing-test.toml
helpers/passing-test2.toml
"""
expected_stderr = ""
expected_exit_code = 0
