program = "echo"


[[test]]
id = "shared"
program_arguments = ["-n", "first"]

expected_stdout = "first"


[[test]]
id = "unique"
program_arguments = ["-n", "second"]

expected_stdout = "second"


[[test]]
id = "shared"
program_arguments = ["-n", "third"]

expected_stdout = "third"


[[test]]
id = "shared"
program_arguments = ["-n", "fourth"]

expected_stdout = "fourth"
