program = "echo"


[[test]]
id = "valid-id"
program_arguments = ["-n", "hello"]

expected_stdout = "hello"


[[test]]
id = "invalid id!"
program_arguments = ["-n", "world"]

expected_stdout = "world"


[[test]]
id = ""
program_arguments = ["-n", "empty"]

expected_stdout = "empty"
