program = "echo"


[[test]]
id = "ambiguous"

expected_stdout = { from_file = "out.txt", from_env = "MY_VAR" }                       # Ambiguous fields
expected_stderr = { from_file = "out.txt", from_env = "MY_VAR", unknown_key = "oops" } # Ambiguous fields + unexpected field


[[test]]
id = "missing-required-keys"

expected_stdout = { unknown_key = "value" } # Unexpected field


[[test]]
id = "from_file"

expected_stdout = { from_file = "x", unknown_key = "oops" } # Valid field + unexpected field
expected_stderr = { from_file = 99 }                        # Valid field, but wrong type
expected_exit_code = { from_file = 99, other_key = false }  # Valid field, but wrong type + unexpected field


[[test]]
id = "from_env"

expected_stdout = { from_env = "MY_VAR", unknown_key = "oops" } # Valid field + unexpected field
expected_stderr = { from_env = 99 }                             # Valid field, but wrong type
expected_exit_code = { from_env = 99, other_key = false }       # Valid field, but wrong type + unexpected field
