input_files = ["helpers"]
program = { from_env = "AUREUM_TEST_EXEC" }


[[test]]
id = "without-verbose"
program_arguments = ["test", "--stable-output", "helpers/*.toml"]

expected_stdout = """
🚀 Running 3 tests:
...

Test result: OK* (3 passed, 3 config errors) — Finished in 0.0s
"""
expected_stderr = """
📋 helpers/many-requirements.toml
├── Watch file errors
│   ├── ✘ missing external file `AUREUM_TEST_FILE_WITH_PATH_TO_WATCH_DOES_NOT_EXIST`
│   └── ✘ missing environment variable `AUREUM_TEST_ENV_VAR_WITH_PATH_TO_WATCH_DOES_NOT_EXIST`
├── :env-var-exists
├── :env-var-missing
│   └── Validation errors
│       └── ✘ field `expected_stdout`: missing environment variable `AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST`
├── :external-file-exists
└── :external-file-missing
    └── Validation errors
        └── ✘ field `expected_stdout`: missing external file `aureum_test_this_file_does_not_exist`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[test]]
id = "with-verbose"
program_arguments = ["test", "--verbose", "--stable-output", "helpers/*.toml"]

expected_stdout = """
🚀 Running 3 tests:
...

✔ helpers/many-requirements.toml:env-var-exists
✔ helpers/many-requirements.toml:external-file-exists
✔ helpers/no-requirements.toml

Test result: OK* (3 passed, 3 config errors) — Finished in 0.0s
"""
expected_stderr = """
🔍 Found 2 config files
├── helpers/many-requirements.toml
└── helpers/no-requirements.toml

📋 helpers/many-requirements.toml
├── Requirements
│   ├── Files
│   │   ├── ✘ AUREUM_TEST_FILE_WITH_PATH_TO_WATCH_DOES_NOT_EXIST
│   │   ├── ✘ aureum_test_this_file_does_not_exist
│   │   └── ✔ hello-world.txt
│   └── Environment variables
│       ├── ✘ AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST
│       ├── ✘ AUREUM_TEST_ENV_VAR_WITH_PATH_TO_WATCH_DOES_NOT_EXIST
│       └── ✔ AUREUM_TEST_HELLO_WORLD
├── Watch files
│   └── hello-world.txt
├── Watch file errors
│   ├── ✘ missing external file `AUREUM_TEST_FILE_WITH_PATH_TO_WATCH_DOES_NOT_EXIST`
│   └── ✘ missing environment variable `AUREUM_TEST_ENV_VAR_WITH_PATH_TO_WATCH_DOES_NOT_EXIST`
├── :env-var-exists
│   └── Program to run
│       └── ✔ <absolute path to 'echo'>
├── :env-var-missing
│   ├── Program to run
│   │   └── ✔ <absolute path to 'echo'>
│   └── Validation errors
│       └── ✘ field `expected_stdout`: missing environment variable `AUREUM_TEST_ENV_VAR_DOES_NOT_EXIST`
├── :external-file-exists
│   └── Program to run
│       └── ✔ <absolute path to 'echo'>
└── :external-file-missing
    ├── Program to run
    │   └── ✔ <absolute path to 'echo'>
    └── Validation errors
        └── ✘ field `expected_stdout`: missing external file `aureum_test_this_file_does_not_exist`

📋 helpers/no-requirements.toml
└── Test
    └── Program to run
        └── ✔ <absolute path to 'echo'>

warning: some config files contain errors (see above)
"""
expected_exit_code = 3
