program = { env = "AUREUM_TEST_EXEC" }


[[test]]
id = "already-formatted"
program_arguments = [
    "format",
    { path_of_file = "helpers/already-formatted.toml" },
]

expected_stdout = ""
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "check-already-formatted"
program_arguments = [
    "format",
    "--check",
    { path_of_file = "helpers/already-formatted.toml" },
]

expected_stdout = ""
expected_stderr = ""
expected_exit_code = 0


[[test]]
id = "check-needs-reformatting"
program_arguments = [
    "format",
    "--check",
    { path_of_file = "helpers/wrong-order.toml" },
]

expected_stdout = ""
expected_stderr = """
helpers/wrong-order.toml
"""
expected_exit_code = 1


[[test]]
id = "check-missing-blank-line-before-tests"
program_arguments = [
    "format",
    "--check",
    { path_of_file = "helpers/no-blank-before-tests.toml" },
]

expected_stdout = ""
expected_stderr = """
helpers/no-blank-before-tests.toml
"""
expected_exit_code = 1
