program = { from_env = "AUREUM_TEST_EXEC" }
program_arguments = ["format", "--help"]

expected_stdout = """
Format config files

Usage: aureum format [OPTIONS] <PATHS>...

Arguments:
  <PATHS>...  Paths to config files

Options:
      --check  Report unformatted files without modifying them
  -h, --help   Print help
"""
expected_stderr = ""
expected_exit_code = 0
