program = { env = "AUREUM_TEST_EXEC" }
program_arguments = ["list", "basic_helpers/*.toml"]

expected_stdout = """
basic_helpers/nested_test.toml:test1
basic_helpers/nested_test.toml:test2
basic_helpers/passing_test.toml
basic_helpers/passing_test2.toml
"""
expected_stderr = ""
expected_exit_code = 0
