program = { env = "AUREUM_TEST_EXEC" }


[[test]]
id = "missing-config"
program_arguments = [
    "test",
    "--record",
    "100x20",
    "aureum_test_this_file_does_not_exist",
]

expected_stdout = ""
expected_stderr = """
warning: invalid paths to config files:
aureum_test_this_file_does_not_exist

error: no config files found for the given paths
"""
expected_exit_code = 3


[[test]]
id = "missing-config-with-test-id"
program_arguments = [
    "test",
    "--record",
    "100x20",
    "aureum_test_this_file_does_not_exist:sub1",
]

expected_stdout = ""
expected_stderr = """
warning: invalid paths to config files:
aureum_test_this_file_does_not_exist:sub1

error: no config files found for the given paths
"""
expected_exit_code = 3
