program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "all_valid.all"
program_arguments = ["test", "--format", "summary", "helpers/all_valid.toml"]

expected_stdout = """
🚀 Running 2 tests:
..

Test result: OK (2 passed, 0 failed)
"""
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "all_valid.specific_test_id"
program_arguments = [
    "test",
    "--format",
    "summary",
    "helpers/all_valid.toml:test1",
]

expected_stdout = """
🚀 Running 1 test:
.

Test result: OK (1 passed, 0 failed)
"""
expected_stderr = ""
expected_exit_code = 0


[[tests]]
id = "missing_program_on_test2.all"
program_arguments = [
    "test",
    "--format",
    "summary",
    "helpers/missing_program_on_test2.toml",
]

expected_stdout = """
🚀 Running 1 test:
.

Test result: OK (1 passed, 0 failed)
"""
expected_stderr = """
📋 helpers/missing_program_on_test2.toml
├── :test1
└── :test2
    └── Validation errors
        └── ✘ The field `program` is required

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3


[[tests]]
id = "missing_program_on_test2.specific_test_id"
program_arguments = [
    "test",
    "--format",
    "summary",
    "helpers/missing_program_on_test2.toml:test1",
]

expected_stdout = """
🚀 Running 1 test:
.

Test result: OK (1 passed, 0 failed)
"""
expected_stderr = """
📋 helpers/missing_program_on_test2.toml
├── :test1
└── :test2
    └── Validation errors
        └── ✘ The field `program` is required

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3


[[tests]]
id = "missing_program_on_all_tests"
program_arguments = [
    "test",
    "--format",
    "summary",
    "helpers/missing_program_on_all_tests.toml",
]

expected_stdout = """
🚀 Running 0 tests:


Test result: OK (0 passed, 0 failed)
"""
expected_stderr = """
📋 helpers/missing_program_on_all_tests.toml
├── :test1
│   └── Validation errors
│       └── ✘ The field `program` is required
└── :test2
    └── Validation errors
        └── ✘ The field `program` is required

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3


[[tests]]
id = "missing_program_on_all_tests.specific_test_id"
program_arguments = [
    "test",
    "--format",
    "summary",
    "helpers/missing_program_on_all_tests.toml:test1",
]

expected_stdout = """
🚀 Running 0 tests:


Test result: OK (0 passed, 0 failed)
"""
expected_stderr = """
📋 helpers/missing_program_on_all_tests.toml
├── :test1
│   └── Validation errors
│       └── ✘ The field `program` is required
└── :test2
    └── Validation errors
        └── ✘ The field `program` is required

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3


[[tests]]
id = "all_files"
program_arguments = ["test", "--format", "summary", "helpers/*.toml"]

expected_stdout = """
🚀 Running 3 tests:
...

Test result: OK (3 passed, 0 failed)
"""
expected_stderr = """
📋 helpers/missing_program_on_all_tests.toml
├── :test1
│   └── Validation errors
│       └── ✘ The field `program` is required
└── :test2
    └── Validation errors
        └── ✘ The field `program` is required

📋 helpers/missing_program_on_test2.toml
├── :test1
└── :test2
    └── Validation errors
        └── ✘ The field `program` is required

warning: Some config files contain errors (See above)
"""
expected_exit_code = 3
