program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "config.empty"
program_arguments = ["validate", "helpers/config_empty.toml"]

expected_stdout = """
✘ helpers/config_empty.toml  1 test
"""
expected_stderr = """
📋 helpers/config_empty.toml
└── Test
    └── Validation errors
        ├── ✘ The field `program` is required
        └── ✘ At least one expectation is required

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "config.no_expectations"
program_arguments = ["validate", "helpers/config_no_expectations.toml"]

expected_stdout = """
✘ helpers/config_no_expectations.toml  1 test
"""
expected_stderr = """
📋 helpers/config_no_expectations.toml
└── Test
    └── Validation errors
        └── ✘ At least one expectation is required

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "config.missing_env_var"
program_arguments = ["validate", "helpers/config_missing_env_var.toml"]

expected_stdout = """
✘ helpers/config_missing_env_var.toml  1 test
"""
expected_stderr = """
📋 helpers/config_missing_env_var.toml
└── Test
    └── Validation errors
        └── ✘ Missing environment variable `AUREUM_TEST_THIS_ENV_VAR_DOES_NOT_EXIST`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "config.missing_external_file"
program_arguments = ["validate", "helpers/config_missing_external_file.toml"]

expected_stdout = """
✘ helpers/config_missing_external_file.toml  1 test
"""
expected_stderr = """
📋 helpers/config_missing_external_file.toml
└── Test
    └── Validation errors
        └── ✘ Missing external file `aureum_test_this_file_does_not_exist`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "program.no_program"
program_arguments = ["validate", "helpers/program_no_program.toml"]

expected_stdout = """
✘ helpers/program_no_program.toml  1 test
"""
expected_stderr = """
📋 helpers/program_no_program.toml
└── Test
    └── Validation errors
        └── ✘ The field `program` is required

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "program.unknown_program"
program_arguments = ["validate", "helpers/program_unknown_program.toml"]

expected_stdout = """
✘ helpers/program_unknown_program.toml  1 test
"""
expected_stderr = """
📋 helpers/program_unknown_program.toml
└── Test
    └── Validation errors
        └── ✘ The program `aureum_test_this_program_does_not_exist` was not found

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "expected_exit_code.invalid_exit_code"
program_arguments = [
    "validate",
    "helpers/expected_exit_code_invalid_exit_code.toml",
]

expected_stdout = """
✘ helpers/expected_exit_code_invalid_exit_code.toml  1 test
"""
expected_stderr = """
📋 helpers/expected_exit_code_invalid_exit_code.toml
└── Test
    └── Validation errors
        └── ✘ Exit code must be a value between -2147483648 to 2147483647 (On POSIX/Unix/Linux: Between 0 and 255)

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "timeout_seconds.negative_timeout"
program_arguments = [
    "validate",
    "helpers/timeout_seconds_negative_timeout.toml",
]

expected_stdout = """
✘ helpers/timeout_seconds_negative_timeout.toml  1 test
"""
expected_stderr = """
📋 helpers/timeout_seconds_negative_timeout.toml
└── Test
    └── Validation errors
        └── ✘ The field `timeout_seconds` must be 0 or greater

warning: some config files contain errors (see above)
"""
expected_exit_code = 3
