program = { env = "AUREUM_TEST_EXEC" }
program_arguments = ["validate", "helpers/negative_timeout.toml"]

expected_stdout = """
✘ helpers/negative_timeout.toml  1 test
"""
expected_stderr = """
📋 helpers/negative_timeout.toml
└── Test
    └── Validation errors
        └── ✘ The field `timeout_seconds` must be 0 or greater

warning: some config files contain errors (see above)
"""
expected_exit_code = 3
