program = { env = "AUREUM_TEST_EXEC" }


[[test]]
id = "wrong-field-types"
program_arguments = ["validate", "helpers/wrong-field-types.toml"]

expected_stdout = """
✘ helpers/wrong-field-types.toml  Parse error
"""
expected_stderr = """
📋 helpers/wrong-field-types.toml
└── Parse errors
    ├── ✘ line 1: field `program`: expected string, got boolean
    ├── ✘ line 2: field `program_arguments`: expected array, got string
    └── ✘ line 4: field `expected_exit_code`: expected integer, got string

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[test]]
id = "wrong-array-element"
program_arguments = ["validate", "helpers/wrong-array-element.toml"]

expected_stdout = """
✘ helpers/wrong-array-element.toml  Parse error
"""
expected_stderr = """
📋 helpers/wrong-array-element.toml
└── Parse errors
    ├── ✘ line 1: field `watch_files`: position 1: expected string, got boolean
    ├── ✘ line 4: field `program_arguments`: position 2: expected string, got integer
    └── ✘ line 4: field `program_arguments`: position 3: expected string, got boolean

warning: some config files contain errors (see above)
"""
expected_exit_code = 3
