program = { env = "AUREUM_TEST_EXEC" }


[[tests]]
id = "unknown_field_at_root"
program_arguments = ["validate", "helpers/unknown-field-at-root.toml"]

expected_stdout = """
✘ helpers/unknown-field-at-root.toml  Parse error
"""
expected_stderr = """
📋 helpers/unknown-field-at-root.toml
└── Parse errors
    └── ✘ unknown field `typo_field`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3


[[tests]]
id = "unknown_field_in_subtest"
program_arguments = ["validate", "helpers/unknown-field-in-subtest.toml"]

expected_stdout = """
✘ helpers/unknown-field-in-subtest.toml  Parse error
"""
expected_stderr = """
📋 helpers/unknown-field-in-subtest.toml
└── Parse errors
    └── ✘ [0]: unknown field `typo_field`

warning: some config files contain errors (see above)
"""
expected_exit_code = 3
