program = { env = "AUREUM_TEST_EXEC" }
program_arguments = [
    "run",
    "--output-format",
    "UNKNOWN",
    "helpers/echo_hello.toml",
]

expected_stdout = ""
expected_stderr = """
error: invalid value 'UNKNOWN' for '--output-format <OUTPUT_FORMAT>': Invalid output format

For more information, try '--help'.
"""
expected_exit_code = 2
